# Generated by Django 5.1.7 on 2025-03-12 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cantidad', models.IntegerField()),
                ('identificador', models.CharField(max_length=12)),
                ('ultima_modificacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
