# Generated by Django 4.2.21 on 2025-05-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
