# Generated by Django 5.2 on 2025-05-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_productos_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id_comentario', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('comentario', models.CharField(max_length=2048)),
            ],
        ),
    ]
